@apiKey = 62237afe89d3fbec955b34f3b9b447948a612c70b591cd5b5837d3aad0a6ac48
@SOLUTION-PROVIDER-EPCIS-URL=http://210.113.134.235:24242/epcis/v2

### Check EPCIS freshness
GET {{SOLUTION-PROVIDER-EPCIS-URL}}/events?
X-API-Key: {{apiKey}}

### ------------------------------------------------------------------------------------------------------------------- V1 Catch  Event
POST {{SOLUTION-PROVIDER-EPCIS-URL}}/capture
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "@context": [
    "https://ref.gs1.org/standards/epcis/epcis-context.jsonld",
    {
      "xsi": "http://www.w3.org/2001/XMLSchema-instance"
    },
    {
      "gdst": "https://traceability-dialogue.org/epcis"
    },
    {
      "sbdh": "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"
    },
    {
      "epcisq": "urn:epcglobal:epcis-query:xsd:1"
    }
  ],
  "type": "EPCISQueryDocument",
  "creationDate": "2022-04-05T11:15:17.0101670-03:00",
  "schemaVersion": "2.0",
  "epcisBody": {
    "queryResults": {
      "queryName": "SimpleEventQuery",
      "subscriptionID": "",
      "resultsBody": {
        "eventList": [
          {
            "type": "ObjectEvent",
            "eventTime": "2022-02-02T11:12:04.4880000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:7cd35bbb-eb86-4f4d-b8a9-2829ad6db946",
            "epcList": [
              "urn:epc:id:sscc:08600031303.0003"
            ],
            "action": "OBSERVE",
            "bizStep": "shipping",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:processor.plant1"
            },
            "sourceList": [
              {
                "type": "owning_party",
                "source": "urn:gdst:example.org:party:processor.1"
              }
            ],
            "destinationList": [
              {
                "type": "owning_party",
                "destination": "urn:gdst:example.org:party:importer.1"
              }
            ],
            "gdst:productOwner": "urn:gdst:example.org:party:importer.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:processor.1"
          },
          {
            "type": "ObjectEvent",
            "eventTime": "2022-02-07T11:12:14.9210000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:756b3c1e-c8c3-4936-beba-0d6001dc571f",
            "epcList": [
              "urn:epc:id:sscc:08600031303.0003"
            ],
            "action": "OBSERVE",
            "bizStep": "receiving",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:importer.123"
            },
            "gdst:productOwner": "urn:gdst:example.org:party:importer.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:importer.1"
          },
          {
            "type": "AggregationEvent",
            "eventTime": "2022-02-01T11:11:25.7520000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:b96a130a-5e4c-4e35-a4ff-8d4fa335890e",
            "parentID": "urn:epc:id:sscc:08600031303.0003",
            "childEPCs": [],
            "action": "ADD",
            "bizStep": "packing",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:processor.plant1"
            },
            "childQuantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:processor.2.v1-0122-2022",
                "quantity": 5000.0,
                "uom": "KGM"
              }
            ],
            "gdst:productOwner": "urn:gdst:example.org:party:processor.1",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                },
                {
                  "gdst:certificationType": "urn:gdst:certType:aggregatorLicense",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:processor.1"
          },
          {
            "type": "AggregationEvent",
            "eventTime": "2022-02-08T11:12:25.7910000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:0b9ef987-71d7-47d8-b80f-9e554fd5e782",
            "parentID": "urn:epc:id:sscc:08600031303.0003",
            "childEPCs": [],
            "action": "DELETE",
            "bizStep": "unpacking",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:importer.123"
            },
            "gdst:productOwner": "urn:gdst:example.org:party:importer.1",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                },
                {
                  "gdst:certificationType": "urn:gdst:certType:aggregatorLicense",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:importer.1"
          },
          {
            "type": "AggregationEvent",
            "eventTime": "2022-03-05T11:11:25.7520000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:b26aca4b-cc32-4032-8e47-7242e5369577",
            "parentID": "urn:epc:id:sscc:08600031303.0003",
            "childEPCs": [],
            "action": "ADD",
            "bizStep": "packing",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:processor.plant1"
            },
            "childQuantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:processor.2.v1-0122-2022",
                "quantity": 5000.0,
                "uom": "KGM"
              }
            ],
            "gdst:productOwner": "urn:gdst:example.org:party:processor.1",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                },
                {
                  "gdst:certificationType": "urn:gdst:certType:aggregatorLicense",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:processor.1"
          },
          {
            "type": "AggregationEvent",
            "eventTime": "2022-03-08T11:12:25.7910000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:fa952b58-18d1-43d6-9534-e41c015b8bb3",
            "parentID": "urn:epc:id:sscc:08600031303.0003",
            "childEPCs": [],
            "action": "DELETE",
            "bizStep": "unpacking",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:importer.123"
            },
            "gdst:productOwner": "urn:gdst:example.org:party:importer.1",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                },
                {
                  "gdst:certificationType": "urn:gdst:certType:aggregatorLicense",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:importer.1"
          }
        ]
      }
    }
  }
}


### ------------------------------------------------------------------------------------------------------------------- V1 Catch  Event
POST {{SOLUTION-PROVIDER-EPCIS-URL}}/capture
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "@context": [
    "https://ref.gs1.org/standards/epcis/epcis-context.jsonld",
    {
      "xsi": "http://www.w3.org/2001/XMLSchema-instance"
    },
    {
      "gdst": "https://traceability-dialogue.org/epcis"
    },
    {
      "sbdh": "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"
    },
    {
      "epcisq": "urn:epcglobal:epcis-query:xsd:1"
    }
  ],
  "type": "EPCISQueryDocument",
  "creationDate": "2022-04-05T11:15:17.0101670-03:00",
  "schemaVersion": "2.0",
  "epcisBody": {
    "queryResults": {
      "queryName": "SimpleEventQuery",
      "subscriptionID": "",
      "resultsBody": {
        "eventList": [
          {
            "type": "TransformationEvent",
            "eventTime": "2022-02-01T08:00:00.0000000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:1392d7b9-59c1-4cc8-97cc-210376504f5e",
            "inputQuantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:processor.10.commingle-01232022",
                "quantity": 9876.0,
                "uom": "KGM"
              }
            ],
            "outputQuantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:processor.2.v1-0122-2022",
                "quantity": 5000.0,
                "uom": "KGM"
              }
            ],
            "transformationID": "transform-1-22-2022-17:24",
            "bizStep": "commissioning",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:processor.plant1"
            },
            "ilmd": {
              "cbvmda:itemExpirationDate": "2023-01-22T03:00:00.0000000+00:00",
              "cbvmda:productionDate": "2022-02-01T08:00:00.0000000+00:00",
              "cbvmda:countryOfOrigin": "US",
              "cbvmda:lotNumber": "V1-0122-2022",
              "cbvmda:certificationList": {
                "certification": [
                  {
                    "gdst:certificationType": "urn:gdst:certType:harvestCert",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:processorLicense",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:humanPolicy",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  }
                ]
              }
            },
            "gdst:productOwner": "urn:gdst:example.org:party:processor.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:informationProvider": "urn:gdst:example.org:party:processor.1"
          }
        ]
      }
    }
  }
}



### ------------------------------------------------------------------------------------------------------------------- V1 Catch  Event
POST {{SOLUTION-PROVIDER-EPCIS-URL}}/capture
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "@context": [
    "https://ref.gs1.org/standards/epcis/epcis-context.jsonld",
    {
      "xsi": "http://www.w3.org/2001/XMLSchema-instance"
    },
    {
      "gdst": "https://traceability-dialogue.org/epcis"
    },
    {
      "sbdh": "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"
    },
    {
      "epcisq": "urn:epcglobal:epcis-query:xsd:1"
    }
  ],
  "type": "EPCISQueryDocument",
  "creationDate": "2022-04-05T11:15:17.0101670-03:00",
  "schemaVersion": "2.0",
  "epcisBody": {
    "queryResults": {
      "queryName": "SimpleEventQuery",
      "subscriptionID": "",
      "resultsBody": {
        "eventList": [
          {
            "type": "TransformationEvent",
            "eventTime": "2022-01-27T11:10:47.2850000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:9b5bd86d-0565-46b2-8167-004956173782",
            "inputQuantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:fishfarm.1.farmed-tuna-01192022",
                "quantity": 12000.0,
                "uom": "KGM"
              },
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:fisherman01.tuna.v1-0122-2022",
                "quantity": 10000.0,
                "uom": "KGM"
              }
            ],
            "outputQuantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:processor.10.commingle-01232022",
                "quantity": 22000.0,
                "uom": "KGM"
              }
            ],
            "bizStep": "urn:gdst:bizStep:commingling",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:processor.plant1"
            },
            "ilmd": {
              "cbvmda:productionDate": "2022-01-23T03:00:00.0000000+00:00",
              "cbvmda:lotNumber": "COMMINGLE-01232022"
            },
            "gdst:productOwner": "urn:gdst:example.org:party:processor.1",
            "cbvmda:informationProvider": "urn:gdst:example.org:party:processor.1"
          }
        ]
      }
    }
  }
}



### ------------------------------------------------------------------------------------------------------------------- V1 Catch  Event
POST {{SOLUTION-PROVIDER-EPCIS-URL}}/capture
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "@context": [
    "https://ref.gs1.org/standards/epcis/epcis-context.jsonld",
    {
      "xsi": "http://www.w3.org/2001/XMLSchema-instance"
    },
    {
      "gdst": "https://traceability-dialogue.org/epcis"
    },
    {
      "sbdh": "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"
    },
    {
      "epcisq": "urn:epcglobal:epcis-query:xsd:1"
    }
  ],
  "type": "EPCISQueryDocument",
  "creationDate": "2022-04-05T11:15:17.0101670-03:00",
  "schemaVersion": "2.0",
  "epcisBody": {
    "queryResults": {
      "queryName": "SimpleEventQuery",
      "subscriptionID": "",
      "resultsBody": {
        "eventList": [
          {
            "type": "ObjectEvent",
            "eventTime": "2022-01-24T11:10:14.0250000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:8b4d7a02-6a04-4a02-b2f6-acd7ab834ba1",
            "epcList": [],
            "action": "OBSERVE",
            "bizStep": "shipping",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:fishfarm.1"
            },
            "quantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:fishfarm.1.farmed-tuna-01192022",
                "quantity": 12000.0,
                "uom": "KGM"
              }
            ],
            "sourceList": [
              {
                "type": "owning_party",
                "source": "urn:gdst:example.org:party:fishfarm.1"
              }
            ],
            "destinationList": [
              {
                "type": "owning_party",
                "destination": "urn:gdst:example.org:party:processor.1"
              }
            ],
            "gdst:productOwner": "urn:gdst:example.org:party:processor.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:fishfarm.1"
          },
          {
            "type": "ObjectEvent",
            "eventTime": "2022-01-25T11:10:18.0370000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:faf23ed1-1946-444e-88e6-7c6cfb47ce9c",
            "epcList": [],
            "action": "OBSERVE",
            "bizStep": "receiving",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:processor.plant1"
            },
            "quantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:fishfarm.1.farmed-tuna-01192022",
                "quantity": 12000.0,
                "uom": "KGM"
              }
            ],
            "gdst:productOwner": "urn:gdst:example.org:party:processor.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:processor.1"
          },
          {
            "type": "TransformationEvent",
            "eventTime": "2022-01-23T11:09:54.5490000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:be1c3f2f-0fb8-4bfd-b569-d283467dba50",
            "inputQuantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:feedmill.1.ff11252021",
                "quantity": 10000.0,
                "uom": "KGM"
              },
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:hatchery.1.tf12012021",
                "quantity": 1000.0,
                "uom": "KGM"
              }
            ],
            "outputQuantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:fishfarm.1.farmed-tuna-01192022",
                "quantity": 12000.0,
                "uom": "KGM"
              }
            ],
            "bizStep": "urn:gdst:bizStep:farmHarvest",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:fishfarm.1"
            },
            "ilmd": {
              "gdst:aquacultureMethod": "intensive ponds",
              "cbvmda:productionMethodForFishAndSeafoodCode": "AQUACULTURE",
              "cbvmda:lotNumber": "FARMED-TUNA-01192022",
              "cbvmda:certificationList": {
                "certification": [
                  {
                    "gdst:certificationType": "urn:gdst:certType:harvestCert",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:humanPolicy",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  }
                ]
              }
            },
            "gdst:productOwner": "urn:gdst:example.org:party:fishfarm.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:informationProvider": "urn:gdst:example.org:party:fishfarm.1"
          }
        ]
      }
    }
  }
}




### ------------------------------------------------------------------------------------------------------------------- V1 Catch  Event
POST {{SOLUTION-PROVIDER-EPCIS-URL}}/capture
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "@context": [
    "https://ref.gs1.org/standards/epcis/epcis-context.jsonld",
    {
      "xsi": "http://www.w3.org/2001/XMLSchema-instance"
    },
    {
      "gdst": "https://traceability-dialogue.org/epcis"
    },
    {
      "sbdh": "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"
    },
    {
      "epcisq": "urn:epcglobal:epcis-query:xsd:1"
    }
  ],
  "type": "EPCISQueryDocument",
  "creationDate": "2022-04-05T11:15:17.0101670-03:00",
  "schemaVersion": "2.0",
  "epcisBody": {
    "queryResults": {
      "queryName": "SimpleEventQuery",
      "subscriptionID": "",
      "resultsBody": {
        "eventList": [
          {
            "type": "ObjectEvent",
            "eventTime": "2022-01-23T10:57:24.1560000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:8aa7928e-539b-43d2-a24c-46f07fdd9291",
            "epcList": [],
            "action": "ADD",
            "bizStep": "urn:gdst:bizStep:fishingEvent",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:epc:id:sgln:08600031303.1.0"
            },
            "quantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:fisherman01.tuna.v1-0122-2022",
                "quantity": 9876.0,
                "uom": "KGM"
              }
            ],
            "ilmd": {
              "cbvmda:vesselCatchInformationList": {
                "cbvmda:vesselCatchInformation": [
                  {
                    "cbvmda:economicZone": "urn:gdst:eez:usa",
                    "cbvmda:fishingGearTypeCode": "urn:gdst:gear:1.1",
                    "cbvmda:vesselFlagState": "US",
                    "cbvmda:vesselID": "VESSEL1",
                    "cbvmda:vesselName": "Vessel #1",
                    "gdst:fisheryImprovementProject": "test",
                    "gdst:gpsAvailability": true,
                    "gdst:imoNumber": "IMO12345678",
                    "gdst:rfmoArea": "urn:gdst:rfmo:cecaf",
                    "gdst:satelliteTrackingAuthority": "test",
                    "gdst:subnationalPermitArea": "test",
                    "gdst:vesselPublicRegistry": "test",
                    "gdst:vesselTripDate": "2022-01-20T10:57:24.1560000+00:00",
                    "cbvmda:catchArea": "urn:gdst:fao:27.1"
                  }
                ]
              },
              "cbvmda:productionMethodForFishAndSeafoodCode": "MARINE_FISHERY",
              "cbvmda:lotNumber": "V1-0122-2022",
              "cbvmda:certificationList": {
                "certification": [
                  {
                    "gdst:certificationType": "urn:gdst:certType:fishingAuth",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:harvestCert",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:humanPolicy",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  }
                ]
              }
            },
            "gdst:productOwner": "urn:gdst:example.org:party:fisherman01.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:informationProvider": "urn:gdst:example.org:party:fisherman01.1"
          },
          {
            "type": "ObjectEvent",
            "eventTime": "2022-01-25T10:58:15.1540000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:763848f6-2900-4afd-b03e-c2e6b9947627",
            "epcList": [],
            "action": "OBSERVE",
            "bizStep": "urn:gdst:bizStep:transshipment",
            "disposition": "active",
            "readPoint": {
              "id": "geo:-34.3232,1.232"
            },
            "bizLocation": {
              "id": "urn:epc:id:sgln:08600031303.3.0"
            },
            "quantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:fisherman01.tuna.v1-0122-2022",
                "quantity": 9876.0,
                "uom": "KGM"
              }
            ],
            "gdst:productOwner": "urn:gdst:example.org:party:fisherman01.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:unloadingPort": "PORTSD",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:transshipmentAuth",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                },
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                },
                {
                  "gdst:certificationType": "urn:gdst:certType:humanPolicy",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:fisherman01.1"
          },
          {
            "type": "ObjectEvent",
            "eventTime": "2022-01-26T11:00:25.1910000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:27911277-3663-4b14-8ba2-2f0f53f0742f",
            "epcList": [],
            "action": "OBSERVE",
            "bizStep": "urn:gdst:bizStep:landing",
            "disposition": "active",
            "readPoint": {
              "id": "geo:0,0"
            },
            "bizLocation": {
              "id": "urn:epc:id:sgln:08600031303.2.0"
            },
            "quantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:fisherman01.tuna.v1-0122-2022",
                "quantity": 9876.0,
                "uom": "KGM"
              }
            ],
            "gdst:productOwner": "urn:gdst:example.org:party:fisherman01.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:unloadingPort": "PORTSD",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:landingAuth",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                },
                {
                  "gdst:certificationType": "urn:gdst:certType:humanPolicy",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:fisherman01.1"
          },
          {
            "type": "ObjectEvent",
            "eventTime": "2022-01-27T07:30:00.0000000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:16a3d836-9223-4ede-ab9b-0ba4cc76c6a4",
            "epcList": [],
            "action": "OBSERVE",
            "bizStep": "shipping",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:epc:id:sgln:08600031303.2.0"
            },
            "quantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:fisherman01.tuna.v1-0122-2022",
                "quantity": 9876.0,
                "uom": "KGM"
              }
            ],
            "gdst:productOwner": "urn:gdst:example.org:party:processor.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:processor.1"
          },
          {
            "type": "ObjectEvent",
            "eventTime": "2022-01-27T08:30:00.0000000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:80700a38-7537-43a7-9031-22256cfff4fd",
            "epcList": [],
            "action": "OBSERVE",
            "bizStep": "receiving",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:processor.plant1"
            },
            "quantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:fisherman01.tuna.v1-0122-2022",
                "quantity": 9876.0,
                "uom": "KGM"
              }
            ],
            "sourceList": [
              {
                "type": "owning_party",
                "source": "urn:gdst:example.org:party:Fisherman01.1"
              }
            ],
            "destinationList": [
              {
                "type": "owning_party",
                "destination": "urn:gdst:example.org:party:processor.1"
              }
            ],
            "gdst:productOwner": "urn:gdst:example.org:party:processor.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:certificationList": {
              "certification": [
                {
                  "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                  "certificationAgency": "test",
                  "certificationStandard": "test",
                  "certificationValue": "test",
                  "certificationIdentification": "test"
                }
              ]
            },
            "cbvmda:informationProvider": "urn:gdst:example.org:party:processor.1"
          }
        ]
      }
    }
  }
}


### ------------------------------------------------------------------------------------------------------------------- V1 Catch  Event
POST {{SOLUTION-PROVIDER-EPCIS-URL}}/capture
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "@context": [
    "https://ref.gs1.org/standards/epcis/epcis-context.jsonld",
    {
      "xsi": "http://www.w3.org/2001/XMLSchema-instance"
    },
    {
      "gdst": "https://traceability-dialogue.org/epcis"
    },
    {
      "sbdh": "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"
    },
    {
      "epcisq": "urn:epcglobal:epcis-query:xsd:1"
    }
  ],
  "type": "EPCISQueryDocument",
  "creationDate": "2022-04-05T11:15:17.0101670-03:00",
  "schemaVersion": "2.0",
  "epcisBody": {
    "queryResults": {
      "queryName": "SimpleEventQuery",
      "subscriptionID": "",
      "resultsBody": {
        "eventList": [
          {
            "type": "ObjectEvent",
            "eventTime": "2021-02-07T11:10:00.0000000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:dbf27f61-4ae7-490c-81ea-999b2f54c28b",
            "epcList": [],
            "action": "ADD",
            "bizStep": "commissioning",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:feedmill.1"
            },
            "quantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:feedmill.1.ff11252021",
                "quantity": 10000.0,
                "uom": "KGM"
              }
            ],
            "ilmd": {
              "gdst:proteinSource": "wild caught",
              "cbvmda:itemExpirationDate": "2022-02-03T03:00:00.0000000+00:00",
              "cbvmda:productionDate": "2022-02-03T03:00:00.0000000+00:00",
              "cbvmda:countryOfOrigin": "US",
              "cbvmda:lotNumber": "FF11252021",
              "cbvmda:certificationList": {
                "certification": [
                  {
                    "gdst:certificationType": "urn:gdst:certType:harvestCert",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:processorLicense",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:humanPolicy",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  }
                ]
              }
            },
            "gdst:productOwner": "urn:gdst:example.org:party:feedmill.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:informationProvider": "urn:gdst:example.org:party:fishfarm.1"
          }
        ]
      }
    }
  }
}


### ------------------------------------------------------------------------------------------------------------------- V1 Catch  Event
POST {{SOLUTION-PROVIDER-EPCIS-URL}}/capture
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "@context": [
    "https://ref.gs1.org/standards/epcis/epcis-context.jsonld",
    {
      "xsi": "http://www.w3.org/2001/XMLSchema-instance"
    },
    {
      "gdst": "https://traceability-dialogue.org/epcis"
    },
    {
      "sbdh": "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"
    },
    {
      "epcisq": "urn:epcglobal:epcis-query:xsd:1"
    }
  ],
  "type": "EPCISQueryDocument",
  "creationDate": "2022-04-05T11:15:17.0101670-03:00",
  "schemaVersion": "2.0",
  "epcisBody": {
    "queryResults": {
      "queryName": "SimpleEventQuery",
      "subscriptionID": "",
      "resultsBody": {
        "eventList": [
          {
            "type": "ObjectEvent",
            "eventTime": "2021-12-05T11:09:40.7930000+00:00",
            "eventTimeZoneOffset": "+00:00",
            "eventID": "urn:uuid:015c0028-d5a2-45ee-abca-d5b044debed7",
            "epcList": [],
            "action": "ADD",
            "bizStep": "urn:gdst:bizStep:hatching",
            "disposition": "active",
            "bizLocation": {
              "id": "urn:gdst:example.org:location:loc:hatchery.1"
            },
            "quantityList": [
              {
                "epcClass": "urn:gdst:example.org:product:lot:class:hatchery.1.tf12012021",
                "quantity": 1000.0,
                "uom": "KGM"
              }
            ],
            "ilmd": {
              "gdst:broodstockSource": "domestic",
              "cbvmda:lotNumber": "TF12012021",
              "cbvmda:certificationList": {
                "certification": [
                  {
                    "gdst:certificationType": "urn:gdst:certType:harvestCert",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  },
                  {
                    "gdst:certificationType": "urn:gdst:certType:humanPolicy",
                    "certificationAgency": "test",
                    "certificationStandard": "test",
                    "certificationValue": "test",
                    "certificationIdentification": "test"
                  }
                ]
              }
            },
            "gdst:productOwner": "urn:gdst:example.org:party:hatchery.1",
            "gdst:humanWelfarePolicy": "3P Audit",
            "cbvmda:informationProvider": "urn:gdst:example.org:party:fishfarm.1"
          }
        ]
      }
    }
  }
}


