urn:epc:id:sscc:08600031303.0003 Done
urn:gdst:example.org:product:lot:class:processor.2.v1-0122-2022 Done

urn:gdst:example.org:product:lot:class:processor.10.commingle-01232022 Done

urn:gdst:example.org:product:lot:class:fishfarm.1.farmed-tuna-01192022 Done

urn:gdst:example.org:product:lot:class:fisherman01.tuna.v1-0122-2022


urn:gdst:example.org:product:lot:class:feedmill.1.ff11252021

urn:gdst:example.org:product:lot:class:hatchery.1.tf12012021




urn:gdst:traceability-solution.com:product:lot:class:8800027.2000002