#Hatching Event
# Larvae or broodstock grown at a hatchery to be stocked in aquaculture facilities are commissioned using an 
#OBJECT - ADD event. These objects (i.e. larvae or other immature progeny) along with feed inputs begin the aquaculture 
#traceability towards full-grown harvested products. For larvae produced in a hatchery, we will use the 
#business step urn:gdst:bizstep:hatching with the disposition active.

#The location (bizLocation) of this event should be the hatchery.

#This event is not used for tracing larvae harvested from the wild.

{
  "@context": [
    "https://ref.gs1.org/standards/epcis/epcis-context.jsonld",
    {
      "xsi": "http://www.w3.org/2001/XMLSchema-instance/"
    },
    {
      "sbdh": "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader/"
    },
    {
      "gdst": "https://traceability-dialogue.org/epcis/"
    }
  ],
  "type": "EPCISDocument",
  "creationDate": "2001-12-17T09:30:47.0000000+00:00",
  "schemaVersion": "2.0",
  "sender": "test",
  "receiver": "test",
  "instanceIdentifier": "9999",
  "epcisBody": {
    "eventList": [
      {
        "type": "ObjectEvent",
        "eventTime": "2020-01-27T00:00:00.0000000-06:00",
        "eventTimeZoneOffset": "+00:00",
        "eventID": "urn:uuid:a2bcc6df-cfdd-42ae-8fc4-bae596d03c11",
        "epcList": [],
        "action": "ADD",
        "bizStep": "urn:gdst:bizstep:hatching",
        "disposition": "active",
        "bizLocation": {
          "id": "urn:gdst:traceability-solution.com:location:loc:dfa01b63-aaaa-4454-b13c-c53d6bdfab43.hatchery"
        },
        "quantityList": [
          {
            "epcClass": "urn:gdst:traceability-solution.com:product:class:dfa01b63-aaaa-4454-b13c-c53d6bdfab43.sal-fry.lot01272020",
            "quantity": 250.0,
            "uom": "KGM"
          }
        ],
        "ilmd": {
          "cbvmda:certificationList": {
            "certification": [
              {
                "gdst:certificationType": "urn:gdst:certType:harvestCert",
                "certificationAgency": "Feed Certificate Authority",
                "certificationStandard": "Feed Certificate Standard",
                "certificationValue": "SIMP.LPCO.2",
                "certificationIdentification": "10161781"
              },
              {
                "gdst:certificationType": "urn:gdst:certType:harvestCoC",
                "certificationAgency": "MSC",
                "certificationStandard": "MSC Chain of Custody",
                "certificationValue": "MSC_COC_1234567890",
                "certificationIdentification": "MSC_COC_1234567890"
              },
              {
                "gdst:certificationType": "urn:gdst:certType:humanyPolicy",
                "certificationAgency": "WHO",
                "certificationStandard": "WHO Human Decency Policy",
                "certificationValue": "1234567890",
                "certificationIdentification": "0987654321"
              }
            ]
          },
          "gdst:broodstockSources": "Domestic"
        },
        "gdst:productOwner": "urn:gdst:traceability-solution.com:party:dfa01b63-aaaa-4454-b13c-c53d6bdfab43",
        "gdst:humanWelfarePolicy": "3P Audit",
        "cbvmda:informationProvider": "urn:gdst:traceability-solution.com:party:dfa01b63-aaaa-4454-b13c-c53d6bdfab43"
      }
    ]
  }
}