
### GDST Digital Link Resolver API Tests

# Variables
#https://id.oliot.org/01/urn:epc:id:sscc:08600031303.0003?linkType=gs1:masterData 
#[{"linkType":"gs1:masterData","link":"http://210.113.134.235:24242/epcis/v2/vocabularies?EQ_name=urn:epc:id:sscc:08600031303.0003","authRequired":true}]

@apiKey = 62237afe89d3fbec955b34f3b9b447948a612c70b591cd5b5837d3aad0a6ac48
@SOLUTION-PROVIDER-URL=http://210.113.134.235:24241/digitallink

@keyType=01
@linkTypeValue=gs1:masterData
@idValue=urn:epc:id:sscc:08600031303.0003
### Health Check
GET http://localhost:4040/health


###
GET http://210.113.134.235:24241/health


### Create Digital Links (Bulk Format)
POST http://localhost:4040/digitallink/new
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "anchor": "/417/8800026900078",
  "itemDescription": "Oliot dl resolver for dl",
  "defaultLinktype": "gs1:epcis",
  "links": [
    {
      "linktype": "gs1:epcis",
      "href": "http://210.113.134.235:24242/epcis/v2",
      "title": "Oliot EPCIS Server",
      "type": "application/json",
      "hreflang": [
        "en"
      ]
    }
  ]
}


###
GET http://localhost:4040/digitallink/417/8800026900078?linkType=gs1:epcis
Accept: application/json
X-API-Key: {{apiKey}}


###
GET {{SOLUTION-PROVIDER-URL}}/417/8800026900078?linkType=gs1:epcis
Accept: application/json
X-API-Key: {{apiKey}}





##2---------  Create Digital Links  00/urn:epc:id:sscc:08600031303.0003 From capability test 

### Post the data 
POST {{SOLUTION-PROVIDER-URL}}/new
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "anchor": "/00/urn:epc:id:sscc:08600031303.0003",
  "itemDescription": "Data From capability",
  "defaultLinktype": "gs1:epcis",
  "links": [
    {
      "linktype": "gs1:epcis",
      "href": "http://210.113.134.235:24242/epcis/v2",
      "title": "EPCIS Event Data",
      "type": "application/json",
      "hreflang": [
        "en"
      ]
    },
    {
      "linktype": "gs1:masterData",
      "href": "http://210.113.134.235:24242/epcis/v2/vocabularies?EQ_name=urn:epc:id:sscc:08600031303.0003",
      "title": "Master Data",
      "type": "application/json",
      "hreflang": [
        "en"
      ]
    }
  ]
}



### Get epcis
GET {{SOLUTION-PROVIDER-URL}}/00/urn:epc:id:sscc:08600031303.0003?linkType=gs1:epcis
Accept: application/json
X-API-Key: {{apiKey}}


### Get epcis
GET {{SOLUTION-PROVIDER-URL}}/00/urn:epc:id:sscc:08600031303.0003?linkType=gs1:masterData
Accept: application/json
X-API-Key: {{apiKey}}





##3---------  Create Digital Links  00/urn:epc:id:sscc:08600031303.0003 For SOLUTION-PROVIDER-GENERATED-EPC

### Post the data 
POST {{SOLUTION-PROVIDER-URL}}/new
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "anchor": "/00/urn:epc:id:sscc:88000269.100000000",
  "itemDescription": "Data From capability",
  "defaultLinktype": "gs1:epcis",
  "links": [
    {
      "linktype": "gs1:epcis",
      "href": "http://210.113.134.235:24242/epcis/v2",
      "title": "EPCIS Event Data",
      "type": "application/json",
      "hreflang": [
        "en"
      ]
    },
    {
      "linktype": "gs1:masterData",
      "href": "http://210.113.134.235:24242/epcis/v2/vocabularies?EQ_name=urn:epc:id:sscc:88000269.100000000",
      "title": "Master Data",
      "type": "application/json",
      "hreflang": [
        "en"
      ]
    }
  ]
}



### Get epcis
GET {{SOLUTION-PROVIDER-URL}}/00/urn:epc:id:sscc:88000269.100000000?linkType=gs1:epcis
Accept: application/json
X-API-Key: {{apiKey}}


### Get epcis
GET {{SOLUTION-PROVIDER-URL}}/00/urn:epc:id:sscc:88000269.100000000?linkType=gs1:masterData
Accept: application/json
X-API-Key: {{apiKey}}



### Get Digital Links for PGLN with EPCIS
GET http://localhost:4040/digitallink/417/urn:epc:pgln:08600031303.0003?linkType=gs1:epcis
Accept: application/json
X-API-Key: {{apiKey}}





### Create Digital Links (Bulk Format)
POST http://localhost:4040/digitallink/new
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "anchor": "/{{keyType}}/{{idValue}}",
  "itemDescription": "Dal Giardino Risotto Rice with Mushrooms 411 gr",
  "defaultLinktype": "gs1:sustainabilityInfo",
  "links": [
    {
      "linktype": "gs1:epcis",
      "href": "https://dalgiardino.com/epcis",
      "title": "EPCIS Event Data",
      "type": "application/json",
      "hreflang": [
        "en"
      ]
    },
    {
      "linktype": "gs1:masterData",
      "href": "https://dalgiardino.com/masterdata/location",
      "title": "Master Data",
      "type": "application/json",
      "hreflang": [
        "en"
      ]
    },
    {
      "linktype": "gs1:hasRetailers",
      "href": "https://dalgiardino.com/where-to-buy/?test_lt=gs1:hasRetailers&test_lang=en",
      "title": "Where to buy",
      "type": "text/html",
      "hreflang": [
        "en"
      ]
    },
    {
      "linktype": "gs1:hasRetailers",
      "href": "https://dalgiardino.com/where-to-buy/index.html.es?test_lt=gs1:hasRetailers&test_lang=es",
      "title": "Donde comprar Dal Giardino",
      "type": "text/html",
      "hreflang": [
        "es"
      ]
    }
  ]
}

### Create Digital Links for PGLN (417)
POST http://localhost:4040/digitallink/new
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "anchor": "/417/urn:epc:pgln:08600031303.0003",
  "itemDescription": "Dal Giardino Company Location",
  "defaultLinktype": "gs1:sustainabilityInfo",
  "links": [
    {
      "linktype": "gs1:epcis",
      "href": "https://dalgiardino.com/epcis",
      "title": "EPCIS Data",
      "type": "application/json",
      "hreflang": [
        "en"
      ]
    },
    {
      "linktype": "gs1:masterData",
      "href": "https://dalgiardino.com/masterdata",
      "title": "Master Data",
      "type": "application/json",
      "hreflang": [
        "en"
      ]
    }
  ]
}

### Get Digital Links by Identifier and LinkType (Using Variables)
GET http://localhost:4040/digitallink/{{keyType}}/{{idValue}}?linkType={{linkTypeValue}}
Accept: application/json
X-API-Key: {{apiKey}}

### Get Digital Links for PGLN with EPCIS
GET http://localhost:4040/digitallink/417/urn:epc:pgln:08600031303.0003?linkType=gs1:epcis
Accept: application/json
X-API-Key: {{apiKey}}

### Get All Digital Links for an Identifier (Master Data)
GET http://localhost:4040/digitallink/{{keyType}}/{{idValue}}?linkType=gs1:masterData
Accept: application/json
X-API-Key: {{apiKey}}

### Get All Links for an Identifier (No Filter)
GET http://localhost:4040/digitallink/{{keyType}}/{{idValue}}
Accept: application/json
X-API-Key: {{apiKey}}

### General Request Pattern
# GET http://localhost:4040/digitallink/{{keyType}}/{{idValue}}?linkType={{linkTypeValue}}
# Accept: application/json
# X-API-Key: {{apiKey}}

### Expected Response Format
# [
#     {
#         "link": "https://dalgiardino.com/epcis",
#         "title": "EPCIS Event Data",
#         "linkType": "gs1:epcis",
#         "ianaLanguage": "en",
#         "context": "",
#         "mimeType": "application/json",
#         "active": true,
#         "fwqs": false,
#         "defaultLinkType": false,
#         "defaultIanaLanguage": true,
#         "defaultContext": false,
#         "defaultMimeType": true,
#         "identifier": "urn:epc:id:sscc:08600031303.0003",
#         "authRequired": false
#     }
# ]


####
{
    "solutionName": "oliopass ver.2.0",
    "version": "2.0",
    "complianceProcessUUID": "991bec22-cd47-49ef-9d91-587075754039",
    "epCs": [
        "urn:epc:id:sscc:08600031303.0003"
    ],
    "gdstVersion": 12,
    "url": "http://210.113.134.235:24241/digitallink",
    "apiKey": "62237afe89d3fbec955b34f3b9b447948a612c70b591cd5b5837d3aad0a6ac48",
    "pgln": "8800026900078"
}




urn:epc:id:sscc:88000269.100000000

be541e06-6d28-4a66-b501-424affe26fdd

9eb1953c-5535-43bc-a3ab-6279789d2b24



{
    "solutionName": "oliopass ver.2.0",
    "version": "2.0",
    "complianceProcessUUID": "a682521e-41f0-4a59-b787-91ebd24d1f36",
    "epCs": [
        "urn:epc:id:sscc:08600031303.0003"
    ],
    "gdstVersion": 12,
    "url": "http://210.113.134.235:24241/digitallink",
    "apiKey": "62237afe89d3fbec955b34f3b9b447948a612c70b591cd5b5837d3aad0a6ac48",
    "pgln": "8800026900078"
}